catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('songs/', views.SongListView.as_view(), name='songs'),
    path('song/<int:pk>', views.SongDetailView.as_view(), name='song-detail'),
]

shuffle/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView
from django.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

# Add URL maps to redirect the base URL to our application
urlpatterns += [
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
]

# Use static() to add URL mapping to serve static files during development (only)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
# Used to generate URLs by reversing the URL patterns
import uuid  # Required for unique song instances
from django.urls import reverse
from django.db import models

# Create your models here.


class Genre(models.Model):
    """Model representing a music genre."""
    name = models.CharField(
        max_length=200, help_text='Enter a music genre (e.g. Rock)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Song(models.Model):
    """Model representing a song (but not a specific copy of a song)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because song can only have one artist, but artists can have multiple songs
    # Author is a string rather than an object because it hasn't been declared yet in the file
    artist = models.ForeignKey('Artist', on_delete=models.SET_NULL, null=True)

    description = models.TextField(
        max_length=1000, help_text='Enter a brief description of the song')
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(
        Genre, help_text='Select a genre for this song')

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this song."""
        return reverse('song-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])
        display_genre.short_description = 'Genre'


class SongInstance(models.Model):
    """Model representing a specific copy of a song."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this particular song across whole site')
    song = models.ForeignKey('Song', on_delete=models.RESTRICT, null=True)
    label = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Song availability',
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.song.title})'


class Artist(models.Model):
    """Model representing an artist."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular artist instance."""
        return reverse('artist-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

catalog/views.py
from django.views import generic
from django.shortcuts import render

# Create your views here.
from .models import Song, Artist, SongInstance, Genre


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_songs = Song.objects.all().count()
    num_instances = SongInstance.objects.all().count()

    # Available songs (status = 'a')
    num_instances_available = SongInstance.objects.filter(
        status__exact='a').count()

    # The 'all()' is implied by default.
    num_artists = Artist.objects.count()

# Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_songs': num_songs,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_artists': num_artists,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class SongListView(generic.ListView):
    model = Song

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(SongListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context


class SongDetailView(generic.DetailView):
    model = Song
    paginate_by = 10

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'songs' %}">All songs</a></li>
                    <li><a href="">All artists</a></li>
                    {% if user.is_authenticated %}
                    <li>User: {{ user.get_username }}</li>
                    <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                    {% endif %}
                </ul>
                {% endblock %}
                {% block pagination %}
                {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
                {% endif %}
                {% endblock %}
            </div>
            <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
        </div>
    </div>
</body>

</html>

catalog/templates/catalog/song_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Title: {{ song.title }}</h1>

<p><strong>Artist:</strong> <a href="">{{ song.artist }}</a></p> <!-- artist detail link not yet defined -->
<p><strong>Summary:</strong> {{ song.summary }}</p>
<p><strong>ISBN:</strong> {{ song.isbn }}</p>
<p><strong>Language:</strong> {{ song.language }}</p>
<p><strong>Genre:</strong> {{ song.genre.all|join:", " }}</p>

<div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in song.songinstance_set.all %}
    <hr>
    <p
        class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
    </p>
    {% if copy.status != 'a' %}
    <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
    {% endif %}
    <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
    <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/song_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Song List</h1>
{% if song_list %}
<ul>
    {% for song in song_list %}
    <li>
        <a href="{{ song.get_absolute_url }}">{{ song.title }}</a> ({{song.artist}})
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no songs in the library.</p>
{% endif %}
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Shuffle Music</h1>
<p>Welcome to Shuffle, a website for <em>local</em> musicians and listeners!</p>
<h2>Dynamic content</h2>
<p>The application has the following record counts:</p>
<ul>
    <li><strong>Songs:</strong> {{ num_songs }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Artists:</strong> {{ num_artists }}</li>
</ul>
<p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>
{% endblock %}